
print(" 500")
print("------")
print("\\              k+1  2k  2k-1")
print(" \\          (-1)   *x  *2")
print("sin(2) => |-------------------")
print(" /           (2*k)!")
print("/")
print("------")
print(" k=1")
